// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtRUHlHV1VW1WQkhz_wn3G7tdCbnAOP0s',
    appId: '1:653463575721:web:67d4ce19bc715dffdaddb8',
    messagingSenderId: '653463575721',
    projectId: 'itri-939f6',
    authDomain: 'itri-939f6.firebaseapp.com',
    storageBucket: 'itri-939f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDgfRuWtU6BrrZju96C6ssNqXYRjnvhA',
    appId: '1:653463575721:android:593d80a9b8720c6edaddb8',
    messagingSenderId: '653463575721',
    projectId: 'itri-939f6',
    storageBucket: 'itri-939f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkI0SLYZ3aaG0IAKqgQ2GlrbV-30P64eE',
    appId: '1:653463575721:ios:e78fad6551c9d617daddb8',
    messagingSenderId: '653463575721',
    projectId: 'itri-939f6',
    storageBucket: 'itri-939f6.firebasestorage.app',
    androidClientId: '653463575721-tlpp8vp9n1s2vv9sk409v76dhgkbllql.apps.googleusercontent.com',
    iosClientId: '653463575721-1s0ujc19c3kactvg2mbse7vdhb35h7f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.itri',
  );

}